version: 14
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 2
  proximityHiderRunnerSize: 4
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000‬
  maximumSize: 4096
  expireAfterAccess: 30000
world:
  - worlds:
      - world
    enabled: true
    darknessBlocks:
      - chest
      - trapped_chest
      - ender_chest
      - spawner
    hiddenBlocks:
      - chest
      - trapped_chest
      - ender_chest
      - coal_ore
      - diamond_ore
      - emerald_ore
      - gold_ore
      - iron_ore
      - lapis_ore
      - redstone_ore
      - shulker_box
      - stone
      - clay
    randomBlocks:
      cave_air: 45
      diamond_ore: 25
      emerald_ore: 10
      gold_ore: 5
      iron_ore: 5
      lapis_ore: 1
      coal_ore: 1
      redstone_ore: 1
      oak_planks: 1
      clay: 1
      cobblestone: 1
      mossy_cobblestone: 1
      obsidian: 1
      stone: 1
      tnt: 1
  - worlds:
      - world_nether
    enabled: true
    darknessBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - spawner
    hiddenBlocks:
      - netherrack
      - nether_quartz_ore
    randomBlocks:
      cave_air: 5
      gravel: 1
      netherrack: 1
      nether_bricks: 1
      nether_quartz_ore: 1
      soul_sand: 1
  - worlds:
      - world_the_end
    enabled: true
    darknessBlocks:
      - chest
      - ender_chest
      - trapped_chest
      - spawner
    hiddenBlocks:
      - end_stone
    randomBlocks:
      cave_air: 5
      bedrock: 1
      end_stone: 1
      end_stone_bricks: 1
      obsidian: 1
      purpur_block: 1

proximity:
  - worlds:
      - world
    enabled: true
    distance: 8
    useFastGazeCheck: false
    hiddenBlocks:
      chest: {}
      trapped_chest: {}
      ender_chest: {}
      emerald_ore: {}
      diamond_ore: {}
      iron_ore: {}
      lapis_ore: {}
      coal_ore: {}
      redstone_ore: {}
      gold_ore: {}
      mossy_cobblestone: {}
      obsidian: {}
      clay: {}
      tnt: {}
      anvil: {}
      damaged_anvil: {}
      crafting_table: {}
      enchanting_table: {}
      furnace: {}
      hopper: {}
      spawner:
        y: 64
        above: false
    randomBlocks:
      cobblestone: 1
      stone: 1
      dirt: 1
      grass_block: 1
