version: 14
general:
  updateOnBlockDamage: true
  bypassNotification: true
  initialRadius: 1
  updateRadius: 22
cache:
  enabled: true
  baseDirectory: 'orebfuscator_cache/'
  maximumOpenRegionFiles: 256
  deleteRegionFilesAfterAccess: 172800000‬
  maximumSize: 4096
  expireAfterAccess: 30000
world:
  - worlds:
      - world
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - CHEST
      - CLAY
      - COAL_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - ENDER_CHEST
      - GOLD_ORE
      - IRON_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
      - SHULKER_BOX
      - STONE
      - TRAPPED_CHEST
    randomBlocks:
      - AIR: 45
      - CLAY
      - COAL_ORE
      - COBBLESTONE
      - DIAMOND_ORE: 25
      - EMERALD_ORE: 10
      - GOLD_ORE: 5
      - IRON_ORE: 5
      - LAPIS_ORE
      - MOSSY_COBBLESTONE
      - OAK_PLANKS
      - OBSIDIAN
      - REDSTONE_ORE
      - STONE
      - TNT
  - worlds:
      - world_nether
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - NETHERRACK
      - NETHER_QUARTZ_ORE
    randomBlocks:
      - AIR: 5
      - GRAVEL
      - NETHERRACK
      - NETHER_BRICKS
      - NETHER_QUARTZ_ORE
      - SOUL_SAND
  - worlds:
      - world_the_end
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - END_STONE
    randomBlocks:
      - AIR: 5
      - BEDROCK
      - END_STONE
      - END_STONE_BRICKS
      - OBSIDIAN
      - PURPUR_BLOCK
