configVersion: 13

updateOnDamage: true
noObfuscationForMetadata: true
noObfuscationForOps: false
noObfuscationForPermission: false
loginNotification: true

maxLoadedCacheFiles: 64
deleteCacheFilesAfterDays: 0
initialRadius: 1
updateRadius: 2

cacheLocation: orebfuscator_cache
noObfuscationForMetadataTagName: NPC

world:
  - worlds:
      - world
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - CHEST
      - CLAY
      - COAL_ORE
      - DIAMOND_ORE
      - EMERALD_ORE
      - ENDER_CHEST
      - GOLD_ORE
      - IRON_ORE
      - LAPIS_ORE
      - REDSTONE_ORE
      - SHULKER_BOX
      - STONE
      - TRAPPED_CHEST
    randomBlocks:
      - CLAY
      - COAL_ORE
      - COBBLESTONE
      - DIAMOND_ORE: 50
      - EMERALD_ORE: 20
      - GOLD_ORE: 10
      - IRON_ORE: 10
      - LAPIS_ORE
      - MOSSY_COBBLESTONE
      - OAK_PLANKS
      - OBSIDIAN
      - REDSTONE_ORE
      - STONE
      - TNT
  - worlds:
      - world_nether
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - NETHERRACK
      - NETHER_QUARTZ_ORE
    randomBlocks:
      - GRAVEL
      - NETHERRACK
      - NETHER_BRICKS
      - NETHER_QUARTZ_ORE
      - SOUL_SAND
  - worlds:
      - world_the_end
    enabled: true
    darknessBlocks:
      - CHEST
      - ENDER_CHEST
      - SPAWNER
      - TRAPPED_CHEST
    hiddenBlocks:
      - END_STONE
    randomBlocks:
      - BEDROCK
      - END_STONE
      - END_STONE_BRICKS
      - OBSIDIAN
      - PURPUR_BLOCK
