# HALLO
ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 1
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Worlds:
  world:
    Enabled: true
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - ENDER_CHEST
    - SPAWNER
    - TRAPPED_CHEST
    Mode1Block: STONE
    RandomBlocks:
    - CLAY
    - COAL_ORE
    - COBBLESTONE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - MOSSY_COBBLESTONE
    - OAK_PLANKS
    - OBSIDIAN
    - REDSTONE_ORE
    - STONE
    - TNT
    ObfuscateBlocks:
    - CHEST
    - CLAY
    - COAL_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - ENDER_CHEST
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - SHULKER_BOX
    - STONE
    - TRAPPED_CHEST
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - CHEST
      - CHIPPED_ANVIL
      - CRAFTING_TABLE
      - DAMAGED_ANVIL
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTING_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - REDSTONE_ORE
      - SHULKER_BOX
      - SPAWNER
      - TRAPPED_CHEST
      UseFastGazeCheck: true
  world_the_end:
    Enabled: true
    Mode1Block: END_STONE
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - ENDER_CHEST
    - SPAWNER
    - TRAPPED_CHEST
    RandomBlocks:
    - BEDROCK
    - END_STONE
    - END_STONE_BRICKS
    - OBSIDIAN
    - PURPUR_BLOCK
    ObfuscateBlocks:
    - END_STONE
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - CHEST
      - CHIPPED_ANVIL
      - CRAFTING_TABLE
      - DAMAGED_ANVIL
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTING_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - REDSTONE_ORE
      - SHULKER_BOX
      - SPAWNER
      - TRAPPED_CHEST
      UseFastGazeCheck: true
  world_nether:
    Enabled: true
    Mode1Block: NETHERRACK
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - ENDER_CHEST
    - SPAWNER
    - TRAPPED_CHEST
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - NETHER_BRICKS
    - NETHER_QUARTZ_ORE
    - SOUL_SAND
    ObfuscateBlocks:
    - NETHERRACK
    - NETHER_QUARTZ_ORE
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - CHEST
      - CHIPPED_ANVIL
      - CRAFTING_TABLE
      - DAMAGED_ANVIL
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTING_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - REDSTONE_ORE
      - SHULKER_BOX
      - SPAWNER
      - TRAPPED_CHEST
      UseFastGazeCheck: true
