ConfigVersion: 13
Booleans:
  UseCache: true
  Enabled: true
  UpdateOnDamage: true
  NoObfuscationForMetadata: true
  NoObfuscationForOps: false
  NoObfuscationForPermission: false
  LoginNotification: true
Integers:
  MaxLoadedCacheFiles: 64
  DeleteCacheFilesAfterDays: 0
  EngineMode: 2
  InitialRadius: 1
  UpdateRadius: 2
Strings:
  CacheLocation: orebfuscator_cache
  NoObfuscationForMetadataTagName: NPC
Worlds:
  world:
    Enabled: true
    Mode1Block: STONE
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - MOB_SPAWNER
    RandomBlocks:
    - CLAY
    - COAL_ORE
    - COBBLESTONE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - MOSSY_COBBLESTONE
    - OBSIDIAN
    - REDSTONE_ORE
    - STONE
    - TNT
    - WOOD
    ObfuscateBlocks:
    - CHEST
    - CLAY
    - COAL_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - ENDER_CHEST
    - GOLD_ORE
    - IRON_ORE
    - LAPIS_ORE
    - REDSTONE_ORE
    - STONE
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - BURNING_FURNACE
      - CHEST
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTMENT_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - MOB_SPAWNER
      - TRAPPED_CHEST
      - WORKBENCH
      UseFastGazeCheck: true
  world_the_end:
    Enabled: true
    Mode1Block: ENDER_STONE
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - MOB_SPAWNER
    RandomBlocks:
    - BEDROCK
    - ENDER_STONE
    - END_BRICKS
    - OBSIDIAN
    - PURPUR_BLOCK
    ObfuscateBlocks:
    - ENDER_STONE
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - BURNING_FURNACE
      - CHEST
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTMENT_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - MOB_SPAWNER
      - TRAPPED_CHEST
      - WORKBENCH
      UseFastGazeCheck: true
  world_nether:
    Enabled: true
    Mode1Block: NETHERRACK
    AntiTexturePackAndFreecam: true
    AirGeneratorMaxChance: 43
    DarknessHideBlocks: false
    BypassObfuscationForSignsWithText: false
    DarknessBlocks:
    - CHEST
    - MOB_SPAWNER
    RandomBlocks:
    - GRAVEL
    - NETHERRACK
    - NETHER_BRICK
    - QUARTZ_ORE
    - SOUL_SAND
    ObfuscateBlocks:
    - NETHERRACK
    - QUARTZ_ORE
    ProximityHider:
      Enabled: true
      Distance: 8
      SpecialBlock: STONE
      Y: 255
      UseSpecialBlock: true
      ObfuscateAboveY: false
      ProximityHiderBlocks:
      - ANVIL
      - BURNING_FURNACE
      - CHEST
      - DIAMOND_ORE
      - DISPENSER
      - EMERALD_ORE
      - ENCHANTMENT_TABLE
      - ENDER_CHEST
      - FURNACE
      - HOPPER
      - MOB_SPAWNER
      - TRAPPED_CHEST
      - WORKBENCH
      UseFastGazeCheck: true
