api-version: 1.21
folia-supported: true

name: ${project.name}
version: ${project.version}

main: net.imprex.api.example.Example

author: Ingrim4

depend: [Orebfuscator]

description: 'Orebfuscator api example project'
