api-version: 1.18

name: orebfuscator-api-example
version: ${project.version}

main: net.imprex.api.example.Example

author: Ingrim4

depend: [Orebfuscator]

description: 'Orebfuscator api example project'
