name: Deploy

on: workflow_dispatch

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build API
      run: |
        mvn clean package -pl orebfuscator-api -B --also-make "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy "-Drevision=$(git describe --tags `git rev-list --tags --max-count=1`)"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_PACKAGE_PAT }}