name: Deploy

on: workflow_dispatch

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Build API
      run: |
        mvn clean package -pl orebfuscator-api -B --also-make -Drevision=$RELEASE_VERSION
    - name: Publish to GitHub Packages
      run: mvn --batch-mode deploy -Drevision=$RELEASE_VERSION