name: Build

on:
  push:
    branches:
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository/org/spigotmc/spigot
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: BuildTools
      run: |
        sh ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package -pl orebfuscator-plugin -B --also-make "-Dorebfuscator.version=$(git describe --tags `git rev-list --tags --max-count=1`)"
        mkdir dist
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./dist
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: Plugin
        path: dist/
