name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: BuildTools cache
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: BuildTools Java 8
      run: |
        sh ./.github/workflows/buildtools.sh java-8
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'temurin'
    - name: BuildTools Java 16
      run: |
        sh ./.github/workflows/buildtools.sh java-16
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: BuildTools Java 17
      run: |
        sh ./.github/workflows/buildtools.sh java-17
    - name: Create maven settings.xml
      uses: s4u/maven-settings-action@v2.4.0
      with:
        servers: '[{ "id": "imprex", "username": "${{ secrets.MAVEN_USER }}", "password": "${{ secrets.MAVEN_PASSWORD }}" }]'
    - name: Build
      run: |
        mvn deploy --batch-mode -Drevision=$RELEASE_VERSION -Daether.connector.basic.threads=1
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "orebfuscator-*.jar"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
