name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set RELEASE_VERSION
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Maven cache
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-${{ hashFiles('./.github/workflows/buildtools.sh') }}
        restore-keys: |
          ${{ runner.os }}-maven-${{ secrets.CACHE_VERSION }}-
    - name: Set up JDK 8/17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: |
          8
          17
    - name: Run BuildTools
      run: |
        bash ./.github/workflows/buildtools.sh
    - name: Build
      run: |
        mvn clean package --batch-mode -Drevision=$RELEASE_VERSION
        mv orebfuscator-plugin/target/orebfuscator-*.jar ./
    - name: Release artifacts
      uses: ncipollo/release-action@v1
      with:
        artifacts: "orebfuscator-*.jar"
        name: Release ${{ env.RELEASE_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
