api-version: 1.13

name: Orebfuscator
version: ${project.version}

main: net.imprex.orebfuscator.Orebfuscator

author: lishid
authors: [Ingrim4, NgLoader, SydMontague, ProgrammerDan, Aleksey-Terzi]

depend: [ProtocolLib]
loadbefore: [ProtocolLib]

load: POSTWORLD

description: 'The most powerful and efficient Anti Xray plugin compatible with most CraftBukkit forks!'

permissions:
  orebfuscator.bypass:
    description: Bypass obfuscation
    default: false
