api-version: 1.13

name: ${project.parent.name}
version: ${project.version}
description: '${project.parent.description}'

main: net.imprex.orebfuscator.Orebfuscator

author: Ingrim4
authors: [NgLoader, lishid, SydMontague, ProgrammerDan, Aleksey-Terzi]

depend: [ProtocolLib]
folia-supported: true

commands:
  orebfuscator:
    aliases: [ofc]
    description: Performs administrative tasks regarding Orebfuscator.
    usage: /<command> [dump]
    permission: orebfuscator.admin
    permission-message: You don't have <permission>

permissions:
  orebfuscator.*:
    default: false
    description: Access to all of Orebfuscator's features
    children:
      orebfuscator.admin: true
      orebfuscator.bypass: true
  orebfuscator.admin:
    default: op
    description: Access to update notifications and commands
  orebfuscator.bypass:
    default: false
    description: Bypass the obfuscation
